# Exclude C++ submodule at project root (not src/nsjail!)
exclude = [
  "./nsjail", # C++ submodule root directory
  "build",
]

# Ignore `F401`(imported but unused), `F403`(import *` used), `E402`(import violations) in `__init__.py`
[lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]

[format]
docstring-code-format = true
